---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - deploy/vars/shared.yml
  tasks:
    - include: deploy/tasks/meta.yml
    - include: deploy/tasks/python.yml
    - include: deploy/tasks/apache.yml
