---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    packages:
      - git
      - curl
      - build-essential
      - libssl-dev
      - python3
      - python3-pip
      - apache2
      - libapache2-mod-wsgi-py3
      - postgresql-client-9.5
      - libpq-dev
      - wget
      - yarn
  tasks:
    - include: deploy/tasks/apt.yml
