# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
