# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='state_i',
        ),
    ]
