# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 12:50
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_bill_state_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='state_i',
            field=django_fsm.FSMIntegerField(default=1),
        ),
    ]
