# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('note_type', models.IntegerField(choices=[(1, 'Bill')], db_index=True)),
                ('title', models.CharField(max_length=511)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
