---
- name: Add Yarn key
  apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    state: present
- name: Add Yarn repo
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
- name: Update the cache
  apt:
    update_cache: yes
- name: Install the APT dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages }}"
