---
- shell: cmp -s requirements.txt "{{ artifact_requirements }}" && echo 1 || echo 0
  args:
    chdir: /usr/app
  register: req_diff
- name: Install the dependencies
  shell: pip3 install -r requirements.txt
  args:
    chdir: /usr/app
  when: req_diff.stdout == "0"
- copy:
    src: requirements.txt
    dest: "{{ artifact_requirements }}"
    owner: ubuntu
    group: ubuntu
