---
apt_dependent:
  - python3
  - python3-pip
  - apache2
  - libapache2-mod-wsgi-py3
  - postgresql-client-9.5
  - libpq-dev
artifacts_dir: /home/ubuntu/.artifacts
artifact_requirements: "{{ artifacts_dir }}/requirements.txt"
